# Generated by Django 5.0.6 on 2024-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_resume_path_alter_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
